### ISSUE TITLE
FR: Make tiles whole block rather than thin slabs

### ISSUE THREAD

**Issue by WulftheNordicRanger** [Andrey2470T/luxury_decor#6]
So one can still place furniture on top of the flooring without messing up the look of their floor

**Comment by Andrey2470T** [comment]
No. Thin slabs is the best variant because its general assignment is to be flat and seen only from one side. In your suggested variant it will be seen from all four sides, thus the tile will even serve as "ceiling tile" if there is a space directly under it what is quite irrational.
