### ISSUE TITLE
Give the option to disable oil spawning

### ISSUE THREAD

**Issue by WulftheNordicRanger** [Andrey2470T/luxury_decor#7]
It creates a needless annoyance while mining and currently has no use, also a potential source of lag for servers since it could (and does) flow into large caves

**Comment by Andrey2470T** [comment]
It can not be disabled as used for cooking a paraffin. I will test out as it is spawned still and if yes, decrease its spawn frequency.

**Comment by WulftheNordicRanger** [comment]
maybe have a craft recipe for the oil then? 'cause I feel like that would be a bit better than having it spawn underground as it is a bit of a nucanse. Maybe having oil be craftable from cooking something called an oilstone? It would keep oil in the game while keeping lag down and make mining a bit less annoying

**Comment by Andrey2470T** [comment]
Hmm, I have thought about adding an oil that will generate in 'solid state'. Then it won`t definitely cause lag. After it is mined, players can melt it in the furnace for crafting the paraffin cakes... yes, I will make it rapidly in 1.1.5!

**Comment by Andrey2470T** [comment]
Done https://github.com/Andrey2470T/luxury_decor/commit/c315f00a310bf7edd19e1d7d29d2b84ff56dffbf
